### ISSUE TITLE
I wonder why you decided to write a new one

### ISSUE THREAD

**Issue by Jebarson** [oleg-shilo/CodeMaidPlus#1]
CodeMaid is a opensource with more than 30 contributors. So I wonder why you decided to write a addon instead of contributing to their repo?

**Comment by oleg-shilo** [comment]
I did offer them this work but they found it difficult to proceed with such a migration/integration.

One of the biggest challenges that CM+ uses Roslyn and CodeMaid does not so it is up to them to decide if they want to bring the beast to their codebase. And they decided not to.

See https://github.com/codecadwallader/codemaid/issues/644

**Comment by Jebarson** [comment]
Makes sense. It could have made a lot of sense if it was a part of CM.
